// <auto-generated />
using System;
using FancyPower3k.DataAccess.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FancyPower3k.DataAccess.Migrations
{
    [DbContext(typeof(FancyPowerDbContext))]
    partial class FancyPowerDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("FancyPower3k.DomainModel.Entities.Consumer", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("ChangedDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DistributionPanelId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<double>("MaxConsumption")
                        .HasColumnType("float");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("PowerConsumption")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.HasIndex("DistributionPanelId");

                    b.ToTable("Consumers");

                    b.HasData(
                        new
                        {
                            Id = "123e4567-e89b-12d3-a456-426614174004",
                            ChangedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Office of Bugs Bunny",
                            DistributionPanelId = "123e4567-e89b-12d3-a456-426614174003",
                            MaxConsumption = 2000.0,
                            Name = "Bugs Bunny Office",
                            PowerConsumption = 1500.0
                        },
                        new
                        {
                            Id = "123e4567-e89b-12d3-a456-426614174005",
                            ChangedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Lab of Daffy Duck",
                            DistributionPanelId = "123e4567-e89b-12d3-a456-426614174003",
                            MaxConsumption = 2500.0,
                            Name = "Daffy Duck Lab",
                            PowerConsumption = 2000.0
                        },
                        new
                        {
                            Id = "123e4567-e89b-12d3-a456-426614174006",
                            ChangedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Secret cave of Batman",
                            DistributionPanelId = "123e4567-e89b-12d3-a456-426614174002",
                            MaxConsumption = 7000.0,
                            Name = "Batman Cave",
                            PowerConsumption = 5000.0
                        });
                });

            modelBuilder.Entity("FancyPower3k.DomainModel.Entities.DistributionPanel", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("ChangedDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LocationId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<double>("MaxPowerDelivery")
                        .HasColumnType("float");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("LocationId");

                    b.ToTable("DistributionPanels");

                    b.HasData(
                        new
                        {
                            Id = "123e4567-e89b-12d3-a456-426614174002",
                            ChangedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Primary distribution panel for Gotham",
                            LocationId = "123e4567-e89b-12d3-a456-426614174001",
                            MaxPowerDelivery = 10000.0,
                            Name = "Main Panel Gotham"
                        },
                        new
                        {
                            Id = "123e4567-e89b-12d3-a456-426614174003",
                            ChangedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Backup distribution panel for Toon Town",
                            LocationId = "123e4567-e89b-12d3-a456-426614174000",
                            MaxPowerDelivery = 5000.0,
                            Name = "Backup Panel Toon"
                        });
                });

            modelBuilder.Entity("FancyPower3k.DomainModel.Entities.Employee", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("ChangedDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateOfBirth")
                        .HasColumnType("datetime2");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("JobTitle")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LocationId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("Position")
                        .HasColumnType("int");

                    b.Property<double>("Salary")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.HasIndex("LocationId");

                    b.ToTable("Employees");

                    b.HasData(
                        new
                        {
                            Id = "123e4567-e89b-12d3-a456-426614174000",
                            ChangedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateOfBirth = new DateTime(1965, 7, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Robert",
                            JobTitle = "CEO",
                            LastName = "Johnson",
                            LocationId = "123e4567-e89b-12d3-a456-426614174000",
                            Position = 5,
                            Salary = 101000.0
                        },
                        new
                        {
                            Id = "123e4567-e89b-12d3-a456-426614174001",
                            ChangedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateOfBirth = new DateTime(1970, 7, 9, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Jennifer",
                            JobTitle = "CFO",
                            LastName = "Williams",
                            LocationId = "123e4567-e89b-12d3-a456-426614174000",
                            Position = 2,
                            Salary = 101000.0
                        },
                        new
                        {
                            Id = "123e4567-e89b-12d3-a456-426614174002",
                            ChangedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateOfBirth = new DateTime(1975, 2, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "William",
                            JobTitle = "HRManager",
                            LastName = "Miller",
                            LocationId = "123e4567-e89b-12d3-a456-426614174000",
                            Position = 6,
                            Salary = 103000.0
                        },
                        new
                        {
                            Id = "123e4567-e89b-12d3-a456-426614174003",
                            ChangedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateOfBirth = new DateTime(1996, 9, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Jennifer",
                            JobTitle = "Developer",
                            LastName = "Johnson",
                            LocationId = "123e4567-e89b-12d3-a456-426614174001",
                            Position = 0,
                            Salary = 80000.0
                        },
                        new
                        {
                            Id = "123e4567-e89b-12d3-a456-426614174004",
                            ChangedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateOfBirth = new DateTime(1981, 10, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "William",
                            JobTitle = "CFO",
                            LastName = "Smith",
                            LocationId = "123e4567-e89b-12d3-a456-426614174000",
                            Position = 1,
                            Salary = 52000.0
                        },
                        new
                        {
                            Id = "123e4567-e89b-12d3-a456-426614174005",
                            ChangedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateOfBirth = new DateTime(1964, 3, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Jennifer",
                            JobTitle = "CEO",
                            LastName = "Davis",
                            LocationId = "123e4567-e89b-12d3-a456-426614174000",
                            Position = 5,
                            Salary = 64000.0
                        },
                        new
                        {
                            Id = "123e4567-e89b-12d3-a456-426614174006",
                            ChangedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateOfBirth = new DateTime(1962, 6, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Robert",
                            JobTitle = "HRManager",
                            LastName = "Miller",
                            LocationId = "123e4567-e89b-12d3-a456-426614174000",
                            Position = 1,
                            Salary = 51000.0
                        },
                        new
                        {
                            Id = "123e4567-e89b-12d3-a456-426614174007",
                            ChangedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateOfBirth = new DateTime(1988, 1, 13, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Michael",
                            JobTitle = "Electrician",
                            LastName = "Smith",
                            LocationId = "123e4567-e89b-12d3-a456-426614174001",
                            Position = 6,
                            Salary = 93000.0
                        },
                        new
                        {
                            Id = "123e4567-e89b-12d3-a456-426614174008",
                            ChangedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateOfBirth = new DateTime(1993, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "David",
                            JobTitle = "Electrician",
                            LastName = "Smith",
                            LocationId = "123e4567-e89b-12d3-a456-426614174001",
                            Position = 5,
                            Salary = 53000.0
                        },
                        new
                        {
                            Id = "123e4567-e89b-12d3-a456-426614174009",
                            ChangedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateOfBirth = new DateTime(1975, 8, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Lisa",
                            JobTitle = "CEO",
                            LastName = "Jones",
                            LocationId = "123e4567-e89b-12d3-a456-426614174001",
                            Position = 1,
                            Salary = 93000.0
                        },
                        new
                        {
                            Id = "123e4567-e89b-12d3-a456-426614174010",
                            ChangedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateOfBirth = new DateTime(1971, 11, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Sarah",
                            JobTitle = "HRManager",
                            LastName = "Jones",
                            LocationId = "123e4567-e89b-12d3-a456-426614174001",
                            Position = 0,
                            Salary = 138000.0
                        },
                        new
                        {
                            Id = "123e4567-e89b-12d3-a456-426614174011",
                            ChangedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateOfBirth = new DateTime(1966, 2, 13, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Emily",
                            JobTitle = "CEO",
                            LastName = "Garcia",
                            LocationId = "123e4567-e89b-12d3-a456-426614174000",
                            Position = 6,
                            Salary = 64000.0
                        },
                        new
                        {
                            Id = "123e4567-e89b-12d3-a456-426614174012",
                            ChangedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateOfBirth = new DateTime(1980, 12, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Michael",
                            JobTitle = "HRManager",
                            LastName = "Miller",
                            LocationId = "123e4567-e89b-12d3-a456-426614174001",
                            Position = 5,
                            Salary = 78000.0
                        },
                        new
                        {
                            Id = "123e4567-e89b-12d3-a456-426614174013",
                            ChangedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateOfBirth = new DateTime(1960, 5, 27, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Lisa",
                            JobTitle = "Electrician",
                            LastName = "Davis",
                            LocationId = "123e4567-e89b-12d3-a456-426614174000",
                            Position = 1,
                            Salary = 76000.0
                        },
                        new
                        {
                            Id = "123e4567-e89b-12d3-a456-426614174014",
                            ChangedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateOfBirth = new DateTime(1976, 2, 28, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Michael",
                            JobTitle = "Electrician",
                            LastName = "Miller",
                            LocationId = "123e4567-e89b-12d3-a456-426614174000",
                            Position = 0,
                            Salary = 82000.0
                        },
                        new
                        {
                            Id = "123e4567-e89b-12d3-a456-426614174015",
                            ChangedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateOfBirth = new DateTime(1960, 1, 24, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Jennifer",
                            JobTitle = "Accountant",
                            LastName = "Rodriguez",
                            LocationId = "123e4567-e89b-12d3-a456-426614174001",
                            Position = 1,
                            Salary = 142000.0
                        },
                        new
                        {
                            Id = "123e4567-e89b-12d3-a456-426614174016",
                            ChangedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateOfBirth = new DateTime(1985, 8, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Michael",
                            JobTitle = "CEO",
                            LastName = "Miller",
                            LocationId = "123e4567-e89b-12d3-a456-426614174000",
                            Position = 1,
                            Salary = 52000.0
                        },
                        new
                        {
                            Id = "123e4567-e89b-12d3-a456-426614174017",
                            ChangedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateOfBirth = new DateTime(1991, 2, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Lisa",
                            JobTitle = "Developer",
                            LastName = "Wilson",
                            LocationId = "123e4567-e89b-12d3-a456-426614174001",
                            Position = 2,
                            Salary = 105000.0
                        },
                        new
                        {
                            Id = "123e4567-e89b-12d3-a456-426614174018",
                            ChangedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateOfBirth = new DateTime(1983, 5, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Jennifer",
                            JobTitle = "CFO",
                            LastName = "Johnson",
                            LocationId = "123e4567-e89b-12d3-a456-426614174000",
                            Position = 2,
                            Salary = 146000.0
                        },
                        new
                        {
                            Id = "123e4567-e89b-12d3-a456-426614174019",
                            ChangedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateOfBirth = new DateTime(1992, 2, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Sarah",
                            JobTitle = "Electrician",
                            LastName = "Wilson",
                            LocationId = "123e4567-e89b-12d3-a456-426614174001",
                            Position = 1,
                            Salary = 144000.0
                        },
                        new
                        {
                            Id = "123e4567-e89b-12d3-a456-426614174020",
                            ChangedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateOfBirth = new DateTime(1976, 2, 26, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "David",
                            JobTitle = "Accountant",
                            LastName = "Miller",
                            LocationId = "123e4567-e89b-12d3-a456-426614174000",
                            Position = 7,
                            Salary = 67000.0
                        },
                        new
                        {
                            Id = "123e4567-e89b-12d3-a456-426614174021",
                            ChangedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateOfBirth = new DateTime(1997, 10, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Sarah",
                            JobTitle = "CEO",
                            LastName = "Davis",
                            LocationId = "123e4567-e89b-12d3-a456-426614174001",
                            Position = 2,
                            Salary = 102000.0
                        },
                        new
                        {
                            Id = "123e4567-e89b-12d3-a456-426614174022",
                            ChangedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateOfBirth = new DateTime(1986, 3, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Michael",
                            JobTitle = "Developer",
                            LastName = "Rodriguez",
                            LocationId = "123e4567-e89b-12d3-a456-426614174000",
                            Position = 6,
                            Salary = 114000.0
                        },
                        new
                        {
                            Id = "123e4567-e89b-12d3-a456-426614174023",
                            ChangedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateOfBirth = new DateTime(1995, 10, 27, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "David",
                            JobTitle = "Accountant",
                            LastName = "Rodriguez",
                            LocationId = "123e4567-e89b-12d3-a456-426614174001",
                            Position = 3,
                            Salary = 139000.0
                        },
                        new
                        {
                            Id = "123e4567-e89b-12d3-a456-426614174024",
                            ChangedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateOfBirth = new DateTime(1968, 8, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Jane",
                            JobTitle = "HRManager",
                            LastName = "Miller",
                            LocationId = "123e4567-e89b-12d3-a456-426614174000",
                            Position = 0,
                            Salary = 130000.0
                        },
                        new
                        {
                            Id = "123e4567-e89b-12d3-a456-426614174025",
                            ChangedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateOfBirth = new DateTime(1968, 7, 23, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Sarah",
                            JobTitle = "ProjectManager",
                            LastName = "Garcia",
                            LocationId = "123e4567-e89b-12d3-a456-426614174000",
                            Position = 1,
                            Salary = 143000.0
                        },
                        new
                        {
                            Id = "123e4567-e89b-12d3-a456-426614174026",
                            ChangedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateOfBirth = new DateTime(1972, 3, 9, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "John",
                            JobTitle = "CEO",
                            LastName = "Williams",
                            LocationId = "123e4567-e89b-12d3-a456-426614174000",
                            Position = 7,
                            Salary = 97000.0
                        },
                        new
                        {
                            Id = "123e4567-e89b-12d3-a456-426614174027",
                            ChangedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateOfBirth = new DateTime(1986, 12, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "David",
                            JobTitle = "MarketingManager",
                            LastName = "Garcia",
                            LocationId = "123e4567-e89b-12d3-a456-426614174001",
                            Position = 2,
                            Salary = 68000.0
                        },
                        new
                        {
                            Id = "123e4567-e89b-12d3-a456-426614174028",
                            ChangedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateOfBirth = new DateTime(1975, 12, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Sarah",
                            JobTitle = "CFO",
                            LastName = "Davis",
                            LocationId = "123e4567-e89b-12d3-a456-426614174001",
                            Position = 7,
                            Salary = 81000.0
                        },
                        new
                        {
                            Id = "123e4567-e89b-12d3-a456-426614174029",
                            ChangedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateOfBirth = new DateTime(1960, 4, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "William",
                            JobTitle = "Electrician",
                            LastName = "Rodriguez",
                            LocationId = "123e4567-e89b-12d3-a456-426614174001",
                            Position = 7,
                            Salary = 91000.0
                        },
                        new
                        {
                            Id = "123e4567-e89b-12d3-a456-426614174030",
                            ChangedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateOfBirth = new DateTime(1971, 12, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Robert",
                            JobTitle = "Electrician",
                            LastName = "Wilson",
                            LocationId = "123e4567-e89b-12d3-a456-426614174000",
                            Position = 2,
                            Salary = 115000.0
                        },
                        new
                        {
                            Id = "123e4567-e89b-12d3-a456-426614174031",
                            ChangedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateOfBirth = new DateTime(1974, 5, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Robert",
                            JobTitle = "ProjectManager",
                            LastName = "Miller",
                            LocationId = "123e4567-e89b-12d3-a456-426614174000",
                            Position = 5,
                            Salary = 110000.0
                        },
                        new
                        {
                            Id = "123e4567-e89b-12d3-a456-426614174032",
                            ChangedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateOfBirth = new DateTime(1965, 11, 9, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Robert",
                            JobTitle = "Accountant",
                            LastName = "Smith",
                            LocationId = "123e4567-e89b-12d3-a456-426614174001",
                            Position = 2,
                            Salary = 50000.0
                        },
                        new
                        {
                            Id = "123e4567-e89b-12d3-a456-426614174033",
                            ChangedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateOfBirth = new DateTime(1967, 8, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Emily",
                            JobTitle = "Accountant",
                            LastName = "Johnson",
                            LocationId = "123e4567-e89b-12d3-a456-426614174000",
                            Position = 1,
                            Salary = 115000.0
                        },
                        new
                        {
                            Id = "123e4567-e89b-12d3-a456-426614174034",
                            ChangedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateOfBirth = new DateTime(1994, 5, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Robert",
                            JobTitle = "CFO",
                            LastName = "Davis",
                            LocationId = "123e4567-e89b-12d3-a456-426614174001",
                            Position = 3,
                            Salary = 69000.0
                        },
                        new
                        {
                            Id = "123e4567-e89b-12d3-a456-426614174035",
                            ChangedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateOfBirth = new DateTime(1986, 5, 19, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Sarah",
                            JobTitle = "Accountant",
                            LastName = "Miller",
                            LocationId = "123e4567-e89b-12d3-a456-426614174000",
                            Position = 5,
                            Salary = 72000.0
                        },
                        new
                        {
                            Id = "123e4567-e89b-12d3-a456-426614174036",
                            ChangedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateOfBirth = new DateTime(1987, 4, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Sarah",
                            JobTitle = "MarketingManager",
                            LastName = "Rodriguez",
                            LocationId = "123e4567-e89b-12d3-a456-426614174001",
                            Position = 3,
                            Salary = 148000.0
                        },
                        new
                        {
                            Id = "123e4567-e89b-12d3-a456-426614174037",
                            ChangedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateOfBirth = new DateTime(1976, 6, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "William",
                            JobTitle = "ProjectManager",
                            LastName = "Smith",
                            LocationId = "123e4567-e89b-12d3-a456-426614174001",
                            Position = 3,
                            Salary = 50000.0
                        },
                        new
                        {
                            Id = "123e4567-e89b-12d3-a456-426614174038",
                            ChangedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateOfBirth = new DateTime(1979, 9, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "David",
                            JobTitle = "Electrician",
                            LastName = "Brown",
                            LocationId = "123e4567-e89b-12d3-a456-426614174000",
                            Position = 1,
                            Salary = 129000.0
                        },
                        new
                        {
                            Id = "123e4567-e89b-12d3-a456-426614174039",
                            ChangedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateOfBirth = new DateTime(1980, 3, 27, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Lisa",
                            JobTitle = "Accountant",
                            LastName = "Wilson",
                            LocationId = "123e4567-e89b-12d3-a456-426614174001",
                            Position = 5,
                            Salary = 113000.0
                        },
                        new
                        {
                            Id = "123e4567-e89b-12d3-a456-426614174040",
                            ChangedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateOfBirth = new DateTime(1962, 2, 26, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Sarah",
                            JobTitle = "HRManager",
                            LastName = "Brown",
                            LocationId = "123e4567-e89b-12d3-a456-426614174000",
                            Position = 7,
                            Salary = 106000.0
                        },
                        new
                        {
                            Id = "123e4567-e89b-12d3-a456-426614174041",
                            ChangedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateOfBirth = new DateTime(1974, 2, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Emily",
                            JobTitle = "HRManager",
                            LastName = "Johnson",
                            LocationId = "123e4567-e89b-12d3-a456-426614174001",
                            Position = 0,
                            Salary = 73000.0
                        },
                        new
                        {
                            Id = "123e4567-e89b-12d3-a456-426614174042",
                            ChangedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateOfBirth = new DateTime(1975, 8, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "William",
                            JobTitle = "MarketingManager",
                            LastName = "Rodriguez",
                            LocationId = "123e4567-e89b-12d3-a456-426614174000",
                            Position = 2,
                            Salary = 104000.0
                        },
                        new
                        {
                            Id = "123e4567-e89b-12d3-a456-426614174043",
                            ChangedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateOfBirth = new DateTime(1963, 7, 23, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "John",
                            JobTitle = "ProjectManager",
                            LastName = "Davis",
                            LocationId = "123e4567-e89b-12d3-a456-426614174001",
                            Position = 5,
                            Salary = 140000.0
                        },
                        new
                        {
                            Id = "123e4567-e89b-12d3-a456-426614174044",
                            ChangedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateOfBirth = new DateTime(1976, 11, 23, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "William",
                            JobTitle = "MarketingManager",
                            LastName = "Brown",
                            LocationId = "123e4567-e89b-12d3-a456-426614174001",
                            Position = 7,
                            Salary = 131000.0
                        },
                        new
                        {
                            Id = "123e4567-e89b-12d3-a456-426614174045",
                            ChangedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateOfBirth = new DateTime(1997, 11, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "John",
                            JobTitle = "HRManager",
                            LastName = "Garcia",
                            LocationId = "123e4567-e89b-12d3-a456-426614174001",
                            Position = 7,
                            Salary = 130000.0
                        },
                        new
                        {
                            Id = "123e4567-e89b-12d3-a456-426614174046",
                            ChangedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateOfBirth = new DateTime(1967, 4, 23, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "David",
                            JobTitle = "CEO",
                            LastName = "Wilson",
                            LocationId = "123e4567-e89b-12d3-a456-426614174001",
                            Position = 4,
                            Salary = 141000.0
                        },
                        new
                        {
                            Id = "123e4567-e89b-12d3-a456-426614174047",
                            ChangedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateOfBirth = new DateTime(1973, 11, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "John",
                            JobTitle = "Electrician",
                            LastName = "Rodriguez",
                            LocationId = "123e4567-e89b-12d3-a456-426614174001",
                            Position = 7,
                            Salary = 63000.0
                        },
                        new
                        {
                            Id = "123e4567-e89b-12d3-a456-426614174048",
                            ChangedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateOfBirth = new DateTime(1961, 7, 19, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Sarah",
                            JobTitle = "CEO",
                            LastName = "Wilson",
                            LocationId = "123e4567-e89b-12d3-a456-426614174001",
                            Position = 1,
                            Salary = 69000.0
                        },
                        new
                        {
                            Id = "123e4567-e89b-12d3-a456-426614174049",
                            ChangedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateOfBirth = new DateTime(1978, 5, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Jane",
                            JobTitle = "Accountant",
                            LastName = "Johnson",
                            LocationId = "123e4567-e89b-12d3-a456-426614174001",
                            Position = 5,
                            Salary = 77000.0
                        });
                });

            modelBuilder.Entity("FancyPower3k.DomainModel.Entities.Location", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ChangedDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Size")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Locations");

                    b.HasData(
                        new
                        {
                            Id = "123e4567-e89b-12d3-a456-426614174000",
                            Address = "123 Toon Town Lane",
                            ChangedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Acme Corporation HQ",
                            Size = 5000
                        },
                        new
                        {
                            Id = "123e4567-e89b-12d3-a456-426614174001",
                            Address = "456 Gotham Ave",
                            ChangedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Wayne Enterprises",
                            Size = 10000
                        });
                });

            modelBuilder.Entity("FancyPower3k.DomainModel.Entities.Consumer", b =>
                {
                    b.HasOne("FancyPower3k.DomainModel.Entities.DistributionPanel", "DistributionPanel")
                        .WithMany("Consumers")
                        .HasForeignKey("DistributionPanelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DistributionPanel");
                });

            modelBuilder.Entity("FancyPower3k.DomainModel.Entities.DistributionPanel", b =>
                {
                    b.HasOne("FancyPower3k.DomainModel.Entities.Location", "Location")
                        .WithMany("DistributionPanels")
                        .HasForeignKey("LocationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Location");
                });

            modelBuilder.Entity("FancyPower3k.DomainModel.Entities.Employee", b =>
                {
                    b.HasOne("FancyPower3k.DomainModel.Entities.Location", "Location")
                        .WithMany("Employees")
                        .HasForeignKey("LocationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Location");
                });

            modelBuilder.Entity("FancyPower3k.DomainModel.Entities.DistributionPanel", b =>
                {
                    b.Navigation("Consumers");
                });

            modelBuilder.Entity("FancyPower3k.DomainModel.Entities.Location", b =>
                {
                    b.Navigation("DistributionPanels");

                    b.Navigation("Employees");
                });
#pragma warning restore 612, 618
        }
    }
}
